FROM node:18 as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

FROM node:18.15.0-bullseye

WORKDIR /usr/src/app
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
USER node
