services:
  backend:
    image: 9ts_backend_dev:latest
    container_name: 9ts_backend_dev
    build:
      dockerfile: Dockerfile.dev
      context: ./backend

    volumes:
      - ./backend:/usr/src/app

    environment:
      - NODE_ENV=development
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

    command: [ "npm", "run", "dev" ]

  frontend:
    image: 9ts_frontend_dev:latest
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./frontend
    container_name: 9ts_frontend_dev
    volumes:
      - ./frontend:/usr/src/app

    environment:
      - NODE_ENV=developemnt

    command: [ "npm", "run", "start-docker" ]

  db:
    container_name: 9ts_db_dev
