version: '3'

services:

  frontend:
    env_file:
      - ./.env
    image: 9ts_frontend_prod:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ./frontend

    container_name: 9ts_frontend_prod
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - backend-frontend

  backend:
    env_file:
      - ./.env
    image: 9ts_backend_prod:latest
    build:
      dockerfile: Dockerfile
      context: ./backend

    container_name: 9ts_backend_prod
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - backend-mongo
      - backend-frontend
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - db
    command: [ "dumb-init", "node", "server.js" ]
  db:
    env_file:
      - ./.env
    image: mongo:5-focal
    container_name: 9ts_db_prod
    expose:
      - ${MONGODB_PORT}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    volumes:
      - mongo_data:/data/db

    networks:
      - backend-mongo

networks:
  backend-frontend:
  backend-mongo:

volumes:
  mongo_data:
